/**
 * INVEST CERTO IMÓVEIS - BASE DE DADOS OFICIAL 2026
 * Dados institucionais reais preservados e catálogo de imóveis de alta liquidez.
 */

const INVEST_CERTO_INFO = {
  name: "Invest Certo Imóveis",
  legalName: "Invest Certo Negócios Imobiliários",
  creci: "PJ - 6623",
  creciIndividual: "6653",
  phone: "(31) 99938-9792",
  phoneRaw: "5531999389792",
  email: "davidsoncorretor1@gmail.com",
  responsibleBroker: "Davidson Corretor",
  address: {
    street: "Rua Freitas de Oliveira, 160",
    neighborhood: "Centro",
    city: "Ibirité",
    state: "MG",
    zipCode: "32400-185",
    full: "Rua Freitas de Oliveira, 160, Centro - Ibirité/MG, CEP 32400-185",
    mapsUrl: "https://maps.google.com/?q=Rua+Freitas+de+Oliveira,+160,+Centro,+Ibirité+-+MG"
  },
  social: {
    instagram: "https://www.instagram.com/investcertoimoveis",
    facebook: "https://www.facebook.com/Invest-Certo-Imoveis-2029307557306083",
    whatsapp: "https://wa.me/5531999389792"
  },
  openingHours: "Segunda a Sexta: 09:00 às 18:00 | Sábados: sob agendamento",
  citiesCovered: ["Ibirité", "Sarzedo", "Belo Horizonte", "Betim", "Contagem"],
  neighborhoodsCovered: [
    "Centro (Ibirité)", "Masterville (Sarzedo)", "Central Park", "Jardim Monsenhor Horta",
    "Eldorado (Parque Durval de Barros)", "Bosques de Ibirité", "Serra Azul (Sarzedo)",
    "Recanto Verde", "Jardim das Flores", "Novo Barreirinho", "São Pedro", "Camargos",
    "Jardim das Rosas", "Jardim Ibirité", "Novo Horizonte", "Marilândia", "Cascata"
  ],
  banks: [
    { name: "Caixa Econômica", logo: "assets/img/banks/caixa.svg", role: "Correspondente Caixa Aqui", tag: "Minha Casa Minha Vida & SBPE" },
    { name: "Banco do Brasil", logo: "assets/img/banks/banco-do-brasil.svg", role: "Crédito Ágil Oficial", tag: "Até 35 Anos para Pagar" },
    { name: "Itaú", logo: "assets/img/banks/itau.svg", role: "Parceiro Credenciado", tag: "Taxas Competitivas & Aprovação em 24h" },
    { name: "Santander", logo: "assets/img/banks/santander.svg", role: "Correspondente Credenciado", tag: "Composição de Renda Familiar" },
    { name: "Bradesco", logo: "assets/img/banks/bradesco.svg", role: "Parceiro Oficial", tag: "Emissão de Contrato Ágil" }
  ]
};

const PROPERTIES_DATA = [
  {
    id: "310",
    code: "#310",
    title: "Casa Moderna com 2 Quartos e Garagem para 2 Carros",
    purpose: "venda",
    type: "casa",
    price: 350000,
    condoFee: 0,
    iptuYear: 680,
    neighborhood: "Novo Horizonte",
    city: "Ibirité",
    state: "MG",
    bedrooms: 2,
    suites: 0,
    bathrooms: 1,
    garageSlots: 2,
    privateArea: 85,
    totalArea: 160,
    tag: "Oportunidade",
    tagType: "opportunity",
    highlight: true,
    financeAvailable: true,
    coverImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?auto=format&fit=crop&w=1200&q=80"
    ],
    features: ["Piso em porcelanato", "Bancadas em granito", "Área de serviço independente", "Quintal privativo", "2 vagas de garagem", "Portão basculante"],
    description: "Excelente oportunidade no bairro Novo Horizonte em Ibirité! Casa linear novíssima, composta por 2 quartos confortáveis e bem ventilados, sala ampla para 2 ambientes, cozinha com bancada em granito escuro, banheiro social revestido até o teto, área de serviço separada e ótimo quintal nos fundos para futuro espaço gourmet. Garagem com vaga para 2 veículos. Próximo a comércios, linhas de ônibus e escolas. Aceita financiamento bancário pela Caixa e uso de FGTS."
  },
  {
    id: "305",
    code: "#305",
    title: "Casa com Quintal Gigante de 370m² e Vista Privilegiada",
    purpose: "venda",
    type: "casa",
    price: 450000,
    condoFee: 0,
    iptuYear: 890,
    neighborhood: "Bosques de Ibirité",
    city: "Ibirité",
    state: "MG",
    bedrooms: 3,
    suites: 1,
    bathrooms: 2,
    garageSlots: 2,
    privateArea: 200,
    totalArea: 370,
    tag: "Terreno 370m²",
    tagType: "highlight",
    highlight: true,
    financeAvailable: true,
    coverImage: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80"
    ],
    features: ["Lote com 370m²", "Espaço para piscina", "Área gourmet coberta", "Suíte master", "Sala com pé direito duplo", "Vista definitiva"],
    description: "Para quem busca espaço de verdade! Imóvel no bairro Bosques de Ibirité com lote espetacular de 370m² e área construída de 200m². São 3 quartos (sendo 1 ampla suíte), sala de estar espaçosa, sala de jantar, cozinha espaçosa com armários, varanda colonial arejada e um quintal verde incrível com potencial para piscina e pomar. Imóvel ideal para famílias que valorizam privacidade, ar puro e tranquilidade."
  },
  {
    id: "284",
    code: "#284",
    title: "Casa Duplex de Alto Padrão com 5 Quartos no Central Park",
    purpose: "venda",
    type: "casa",
    price: 650000,
    condoFee: 0,
    iptuYear: 1200,
    neighborhood: "Central Park",
    city: "Ibirité",
    state: "MG",
    bedrooms: 5,
    suites: 1,
    bathrooms: 3,
    garageSlots: 4,
    privateArea: 360,
    totalArea: 360,
    tag: "Alto Padrão",
    tagType: "premium",
    highlight: true,
    financeAvailable: true,
    coverImage: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=1200&q=80"
    ],
    features: ["5 quartos amplos", "Garagem para 4 carros", "Espaço gourmet com churrasqueira", "Varanda com vista panorâmica", "Acabamento de luxo", "Localização nobre"],
    description: "Mansão duplex imponente no bairro nobre Central Park em Ibirité. Edificada com padrão construtivo impecável em lote de 360m², oferecendo 5 dormitórios generosos (1 suíte com closet), 3 banheiros decorados, salão em 2 ambientes, cozinha planejada moderna, espaço gourmet integrado para recepções e garagem coberta para 4 veículos grandes. Localização estratégica e vizinhança de alto nível."
  },
  {
    id: "283",
    code: "#283",
    title: "Residência Contemporânea de Luxo no Monsenhor Horta",
    purpose: "venda",
    type: "casa",
    price: 1690000,
    condoFee: 0,
    iptuYear: 2400,
    neighborhood: "Jardim Monsenhor Horta - 1ª Seção",
    city: "Ibirité",
    state: "MG",
    bedrooms: 4,
    suites: 4,
    bathrooms: 5,
    garageSlots: 4,
    privateArea: 420,
    totalArea: 450,
    tag: "Exclusividade",
    tagType: "exclusive",
    highlight: true,
    financeAvailable: true,
    coverImage: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687644-c7171b42498b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80"
    ],
    features: ["4 suítes plenas", "Piscina aquecida com cascata", "Espaço gourmet climatizado", "Energia solar fotovoltaica", "Home cinema", "Segurança perimetral completa"],
    description: "A propriedade mais exclusiva da região! Arquitetura moderna assinada, pé-direito duplo com iluminação natural abundante e acabamentos nobres em mármore importado e esquadrias de alumínio preto. Composta por 4 suítes climatizadas (master com hidromassagem e closet), área de lazer privativa com piscina com deck e iluminação em LED, espaço gourmet completo e 4 vagas. Um oásis particular no melhor ponto do Jardim Monsenhor Horta."
  },
  {
    id: "241",
    code: "#241",
    title: "Casa Nova com 3 Quartos e Fachada Imponente no Masterville",
    purpose: "venda",
    type: "casa",
    price: 694000,
    condoFee: 0,
    iptuYear: 950,
    neighborhood: "Masterville",
    city: "Sarzedo",
    state: "MG",
    bedrooms: 3,
    suites: 1,
    bathrooms: 3,
    garageSlots: 2,
    privateArea: 185,
    totalArea: 200,
    tag: "Pronto para Morar",
    tagType: "ready",
    highlight: true,
    financeAvailable: true,
    coverImage: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566752229-250ed79470f8?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80"
    ],
    features: ["Fachada contemporânea com ripado", "Suíte com sacada", "Área gourmet com churrasqueira a carvão", "Preparação para aquecimento solar", "Gesso rebaixado e LED", "Bairro planejado com segurança"],
    description: "Viva no Masterville, o bairro mais desejado de Sarzedo! Casa de 3 dormitórios, sendo 1 suíte elegante com varanda, sala com conceito aberto integrada à cozinha americana com ilha em granito escovado, lavabo social, lavanderia coberta e área gourmet completa nos fundos. Acabamento refinado com piso porcelanato acetinado 80x80 e iluminação indireta."
  },
  {
    id: "266",
    code: "#266",
    title: "Linda Casa Linear com 3 Dormitórios no Recanto Verde",
    purpose: "venda",
    type: "casa",
    price: 450000,
    condoFee: 0,
    iptuYear: 750,
    neighborhood: "Recanto Verde",
    city: "Ibirité",
    state: "MG",
    bedrooms: 3,
    suites: 1,
    bathrooms: 2,
    garageSlots: 2,
    privateArea: 130,
    totalArea: 180,
    tag: "Financia 100%",
    tagType: "finance",
    highlight: false,
    financeAvailable: true,
    coverImage: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80"
    ],
    features: ["100% plana / linear", "Suíte ampla", "Quintal gramado", "Cozinha com armários", "2 vagas paralelas"],
    description: "Excelente casa linear no bairro Recanto Verde em Ibirité. Planta funcional sem degraus, perfeita para todas as idades. Conta com 3 dormitórios (1 suíte), sala de jantar e estar integradas, cozinha arejada, banheiros com box blindex e quintal ensolarado nos fundos. Aceita FGTS e aprovação rápida em todos os bancos."
  },
  {
    id: "258",
    code: "#258",
    title: "Casa Aconchegante com 3 Vagas no Jardim das Flores",
    purpose: "venda",
    type: "casa",
    price: 380000,
    condoFee: 0,
    iptuYear: 620,
    neighborhood: "Jardim das Flores",
    city: "Ibirité",
    state: "MG",
    bedrooms: 3,
    suites: 1,
    bathrooms: 2,
    garageSlots: 3,
    privateArea: 110,
    totalArea: 170,
    tag: "Preço Reduzido",
    tagType: "opportunity",
    highlight: false,
    financeAvailable: true,
    coverImage: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80"
    ],
    features: ["3 vagas de garagem", "Quintal privativo", "Cozinha americana", "Próximo a transporte público"],
    description: "Bela residência no Jardim das Flores com 3 quartos (1 suíte), sala ampla, cozinha americana moderna, acabamentos em granito e 3 vagas de garagem. Bairro tranquilo, arborizado e com fácil acesso ao centro comercial de Ibirité."
  },
  {
    id: "251",
    code: "#251",
    title: "Casa Triplex com 3 Suítes no Eldorado (Durval de Barros)",
    purpose: "venda",
    type: "casa",
    price: 450000,
    condoFee: 0,
    iptuYear: 820,
    neighborhood: "Eldorado (Parque Durval de Barros)",
    city: "Ibirité",
    state: "MG",
    bedrooms: 3,
    suites: 3,
    bathrooms: 3,
    garageSlots: 2,
    privateArea: 140,
    totalArea: 140,
    tag: "3 Suítes",
    tagType: "highlight",
    highlight: false,
    financeAvailable: true,
    coverImage: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80"
    ],
    features: ["Todas as 3 suítes plenas", "Terraço panorâmico", "Excelente localização junto a Contagem", "Piso porcelanato"],
    description: "Localização estratégica no Parque Durval de Barros, divisa com Contagem. Imóvel diferenciado onde cada dormitório é uma suíte privativa com varanda. Conta ainda com terraço descoberto para área gourmet com vista panorâmica."
  },
  {
    id: "236",
    code: "#236",
    title: "Casa em Lote de 250m² no Serra Azul com Potencial Construtivo",
    purpose: "venda",
    type: "casa",
    price: 300000,
    condoFee: 0,
    iptuYear: 510,
    neighborhood: "Serra Azul",
    city: "Sarzedo",
    state: "MG",
    bedrooms: 2,
    suites: 0,
    bathrooms: 1,
    garageSlots: 2,
    privateArea: 120,
    totalArea: 250,
    tag: "Lote Amplo 250m²",
    tagType: "opportunity",
    highlight: false,
    financeAvailable: true,
    coverImage: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80"
    ],
    features: ["Lote de 250m²", "Dois pavimentos", "Área para ampliação", "Vista para as serras"],
    description: "Casa de dois pavimentos construída em lote inteiro de 250m² no bairro Serra Azul em Sarzedo. Ideal para quem quer morar e ainda ter amplo espaço para expandir, construir piscina ou montar oficina particular."
  },
  {
    id: "A101",
    code: "#A101",
    title: "Apartamento com Área Privativa em U no Centro de Ibirité",
    purpose: "venda",
    type: "apartamento",
    price: 320000,
    condoFee: 180,
    iptuYear: 580,
    neighborhood: "Centro",
    city: "Ibirité",
    state: "MG",
    bedrooms: 2,
    suites: 1,
    bathrooms: 2,
    garageSlots: 1,
    privateArea: 84,
    totalArea: 110,
    tag: "Área Privativa",
    tagType: "highlight",
    highlight: true,
    financeAvailable: true,
    coverImage: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80"
    ],
    features: ["Área privativa externa em U", "Elevador social", "Vaga demarcada e coberta", "Água individualizada", "A 200m da Igreja Matriz"],
    description: "Apartamento exclusivo no coração de Ibirité! Imóvel com área privativa em 'U' que circunda o apartamento, permitindo criar um belo jardim de inverno e espaço gourmet particular. Prédio individual com fachada moderna e condomínio econômico."
  },
  {
    id: "COB01",
    code: "#COB01",
    title: "Cobertura Duplex com Vista 360° e Espaço Gourmet",
    purpose: "venda",
    type: "cobertura",
    price: 520000,
    condoFee: 220,
    iptuYear: 980,
    neighborhood: "Centro",
    city: "Ibirité",
    state: "MG",
    bedrooms: 3,
    suites: 1,
    bathrooms: 3,
    garageSlots: 2,
    privateArea: 165,
    totalArea: 165,
    tag: "Cobertura Duplex",
    tagType: "premium",
    highlight: true,
    financeAvailable: true,
    coverImage: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80"
    ],
    features: ["Terraço descoberto com vista panorâmica", "Churrasqueira gourmet", "2 vagas cobertas sob pilotis", "Prédio com apenas 8 unidades"],
    description: "Cobertura duplex de alto padrão no Centro de Ibirité. No 1º nível: 2 quartos (1 suíte), banho social, sala em porcelanato e cozinha. No 2º nível: 1 quarto adicional ou home-office, sala de TV privativa, banheiro e amplo terraço aberto com linda vista definitiva."
  },
  {
    id: "LOT01",
    code: "#LOT01",
    title: "Lote Plano de 360m² no Central Park com Escritura e Registro",
    purpose: "venda",
    type: "lote",
    price: 240000,
    condoFee: 0,
    iptuYear: 420,
    neighborhood: "Central Park",
    city: "Ibirité",
    state: "MG",
    bedrooms: 0,
    suites: 0,
    bathrooms: 0,
    garageSlots: 0,
    privateArea: 360,
    totalArea: 360,
    tag: "Pronto para Construir",
    tagType: "ready",
    highlight: false,
    financeAvailable: true,
    coverImage: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80"
    ],
    features: ["Topografia 100% plana", "Rua asfaltada com saneamento e iluminação", "Documentação completa", "Financiamento de terreno e construção Caixa"],
    description: "Excelente lote residencial no bairro nobre Central Park. Topografia plana, frente de 12 metros, solo firme e documentação 100% regularizada. Possibilidade de financiamento conjunto de aquisição de terreno e construção pela Caixa Econômica Federal."
  },
  {
    id: "L01",
    code: "#L01",
    title: "Casa para Locação Comercial ou Residencial no Centro",
    purpose: "locacao",
    type: "casa",
    price: 2200,
    condoFee: 0,
    iptuYear: 80,
    neighborhood: "Centro",
    city: "Ibirité",
    state: "MG",
    bedrooms: 3,
    suites: 1,
    bathrooms: 2,
    garageSlots: 2,
    privateArea: 135,
    totalArea: 200,
    tag: "Para Morar ou Empresa",
    tagType: "highlight",
    highlight: true,
    financeAvailable: false,
    coverImage: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80"
    ],
    features: ["Ponto comercial ou residencial", "Fácil acesso a bancos e cartórios", "Sem fiador (Garantia por Cartão ou Seguro Fiança)", "Quintal amplo"],
    description: "Imóvel muito bem situado no Centro de Ibirité, a poucos passos da Prefeitura, cartórios e principais agências bancárias. Perfeito para consultórios, escritórios de advocacia ou moradia familiar com total comodidade."
  },
  {
    id: "L02",
    code: "#L02",
    title: "Apartamento Novo para Locação no Masterville em Sarzedo",
    purpose: "locacao",
    type: "apartamento",
    price: 1450,
    condoFee: 150,
    iptuYear: 50,
    neighborhood: "Masterville",
    city: "Sarzedo",
    state: "MG",
    bedrooms: 2,
    suites: 0,
    bathrooms: 1,
    garageSlots: 1,
    privateArea: 58,
    totalArea: 70,
    tag: "Primeira Locação",
    tagType: "ready",
    highlight: false,
    financeAvailable: false,
    coverImage: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80"
    ],
    features: ["Primeira moradia", "Armários planejados na cozinha e banheiro", "Vaga demarcada", "Locação sem fiador"],
    description: "Apartamento novinho em folha no Masterville em Sarzedo. Composto por 2 quartos, sala com varanda, cozinha com armários planejados, banheiro moderno com espelho e box blindex. Aluguel descomplicado e aprovação ágil."
  },
  {
    id: "C01",
    code: "#C01",
    title: "Sala Comercial Pronta para Consultório no Centro de Ibirité",
    purpose: "venda",
    type: "comercial",
    price: 195000,
    condoFee: 160,
    iptuYear: 450,
    neighborhood: "Centro",
    city: "Ibirité",
    state: "MG",
    bedrooms: 0,
    suites: 0,
    bathrooms: 1,
    garageSlots: 1,
    privateArea: 42,
    totalArea: 55,
    tag: "Investimento / Renda",
    tagType: "opportunity",
    highlight: false,
    financeAvailable: true,
    coverImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80"
    ],
    features: ["Prédio corporativo com portaria", "Elevador", "Vaga privativa", "Piso em granito", "Recepção montada"],
    description: "Oportunidade ideal para investidores ou profissionais liberais (médicos, dentistas, psicólogos, contadores). Sala comercial com excelente acústica, banheiro interno, ar-condicionado instalado e 1 vaga de garagem no subsolo."
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { INVEST_CERTO_INFO, PROPERTIES_DATA };
}
